export const TyranCommandAction = {
	// Development utilities commands
	DEV_MODE_STATE_UPDATE: 'DEV_MODE_STATE_UPDATE',
	// Client commands
	CLIENT_INFO: 'CLIENT_INFO',
	SET_NICKNAME: 'SET_NICKNAME',
	// Lobby commands
	CREATE_LOBBY: 'CREATE_LOBBY',
	GET_LOBBY_INFO: 'GET_LOBBY_INFO',
	JOIN_LOBBY: 'JOIN_LOBBY',
	UPDATE_LOBBY_INFO: 'UPDATE_LOBBY_INFO',
	SWITCH_TEAM: 'SWITCH_TEAM',
	TRIGGER_GAME_START: 'TRIGGER_GAME_START',
	START_GAME: 'START_GAME',
	ADD_AI_PLAYER: 'ADD_AI_PLAYER',
	KICK_PLAYER: 'KICK_PLAYER',
	KICK_LEAVE_LOBBY: 'KICK_LEAVE_LOBBY',
} as const satisfies Record<string, string>;
