export const TyranError = {
  LOBBY_NOT_FOUND: 'LOBBY_NOT_FOUND',
  LOBBY_FULL: 'LOBBY_FULL',
  INVALID_CODE: 'INVALID_CODE',
  NOT_HOST: 'NOT_HOST',
  GAME_ALREADY_STARTED: 'GAME_ALREADY_STARTED',
  NOT_IN_LOBBY: 'NOT_IN_LOBBY',
  NOT_ENOUGH_PLAYERS: 'NOT_ENOUGH_PLAYERS',
  PLAYER_NOT_FOUND: 'PLAYER_NOT_FOUND',
  TEAM_FULL: 'TEAM_FULL',
} as const;