export const TyranCommandAction = {
	DEV_MODE_STATE_UPDATE: 'DEV_MODE_STATE_UPDATE',
	CLIENT_INFO: 'CLIENT_INFO',
	SET_NICKNAME: 'SET_NICKNAME',
	CREATE_LOBBY: 'CREATE_LOBBY',
	GET_LOBBY_INFO: 'GET_LOBBY_INFO',
	JOIN_LOBBY: 'JOIN_LOBBY',
	UPDATE_LOBBY_INFO: 'UPDATE_LOBBY_INFO',
	SWITCH_TEAM: 'SWITCH_TEAM',
} as const satisfies Record<string, string>;
